[package]
name = "futurecore"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
cxx = "1.0.192"

[build-dependencies]
cmake = "0.1.57"
cxx-build = "1.0.192"
pkg-config = "0.3.32"
